#
#NickNameHistory Config
#Made By horyu1234
#
#Copyright 2014 ~ 2015 . horyu1234 . All rights reserved
#
#플러그인의 EULA에 동의하신다면 EULA 옵션을 true 로 바꿔주세요.
#EULA를 동의하셔야만 플러그인의 사용이 가능합니다.
#
#EULA: https://horyu1234.com/EULA

EULA: false
DateFormat: "yyyy년MM월dd일_hh시mm분ss초"