name: NickNameHistory
main: com.horyu1234.nicknamehistory.NickNameHistory
version: 1.4
author: horyu1234

commands:
  nh:
    description: NickNameHistory Command.
  nhn:
    description: NickNameHistory Command.